spring.jpa.hibernate.ddl-auto=none

spring.datasource.url=jdbc:postgresql://localhost:5432/onestomanys
spring.datasource.username=michael
spring.datasource.password=

spring.sql.init.mode=always
spring.h2.console.enabled=false