spring.datasource.url=jdbc:postgresql://localhost:5432/onestomanys
spring.datasource.username=michael
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=never
spring.h2.console.enabled=false